blank_issues_enabled: false
contact_links:
  - name: 🫶 Support portal
    about: Get support using through our support website.
    url: https://support.blankethub.loxalhost
  - name: 💬 Chat on Discord
    about: Join our Discord server to chat about Blankethub.
    url: https://discord.blankethub.loxalhost
